### ISSUE TITLE
It doesn't work with Samsung SCX-3400 + Archlinux + CM13

### ISSUE THREAD

**Issue by NerosTie** [BenoitDuffez/AndroidCupsPrint#25] opened 2016-11-21 16:58 UTC
From my Android (CM13), the printer (SCX-3400) is detected but when I want to print, I have this error:

`Can't create handler inside thread that has not called Looper.prepare()`

Then `This printer is not available`. 

The printer is not wired to the computer with a USB cable, it's on the local network with Wifi.

**Comment by BenoitDuffez** [comment] 2016-11-21 18:22
Do you use v1.3? This bug was already fixed, so unless you're on the latest version I'm going to close this issue.

**Comment by NerosTie** [comment] 2016-11-21 18:53
The version is 1.3.0b2 from f-droid.

**Comment by BenoitDuffez** [comment] 2016-11-21 20:21
Weird, my merge request for v1.3.0b2 to fdroid was bogus and rejected. I don't know exactly what is build under this version. I'll publish another merge request (likely for 1.3.1) and we'll see if this happens.

Also, fdroid refuses non-free software, so I don't have any crash logging function for the fdroid builds. I don't have any log or stack trace to investigate, so if you can provide the logcat from your device, this would help me a lot troubleshoot this issue.

**Comment by NerosTie** [comment] 2016-11-21 22:04
>  so if you can provide the logcat from your device

```
11-21 22:58:35.125 16681 16681 D CUPS    : onStartPrinterStateTracking: PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://192.168.1.107:631/printers/printer}
11-21 22:58:35.126 16681 16949 I CUPS    : Checking printer status: PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://192.168.1.107:631/printers/printer}
11-21 22:58:35.136 10346 10772 D audio_hw_primary: start_output_stream: exit
11-21 22:58:35.219 16681 16949 E CUPS    : Printer not responding. Printer on fire?
11-21 22:58:35.219 16681 16949 E CUPS    : Failed to check printer PrinterId{serviceName=io.github.benoitduffez.cupsprint/io.github.benoitduffez.cupsprint.printservice.CupsService, localId=http://192.168.1.107:631/printers/printer}: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
```

I think I know why. Look at the IP. It's the IP of the printer which have an internal web server (maybe a CUPS server?). But I think the IP should be my computer, right?

**Comment by NerosTie** [comment] 2016-11-21 22:40
Ok I was right. I needed to "share the printer" on KDE + open the port 631... Now it works. Great work ;)

**Comment by BenoitDuffez** [comment] 2016-11-22 00:23
Thanks for the feedback :)

Also what's weird is that you seem to have discovered a bug with the Looper thing. I'll have to check this though. Reopening for this, because it shouldn't crash (instead, display a nice error message explaining what happened).

**Comment by NerosTie** [comment] 2016-11-22 02:01
> Printer on fire?

Could be the best message we can have ;)

Also, is it possible to exclude a choice from the list? Because now it detects 2 printers but one of them is wrong and I want to hide it.

**Comment by BenoitDuffez** [comment] 2017-01-10 23:10
Do you use https by any chance? That's what I had at some point, and I don't know why but the server keeps advertising itself over http or something.
There is code to remove the http version if https is available, but I'll have to double check this.

If it's not that, can you tell me more about the 2 printers? (e.g. their respective URIs for example)

**Comment by NerosTie** [comment] 2017-01-11 00:36
> Do you use https by any chance?

https on a local network? No, I don't think so. 

> If it's not that, can you tell me more about the 2 printers?

It's not 2 printers, but there are 2 servers for one printer. One of them is my computer with cups (it's ok) and the second one is the internal server of the printer and, sadly, it doesn't work with your app. It's a proprietary software from Samsung and your app should ignore it to avoid any confusion.

**Comment by BenoitDuffez** [comment] 2017-03-19 08:55
I can't find where this issue occurred because the code changed too much since then.

I'm closing this, but please reopen if you can reproduce the issue and give reproduction steps.

**Closed by BenoitDuffez** 2017-03-19 08:55 UTC
Labels: bug
