### ISSUE TITLE
Pull custom paper sizes from ppds on server

### ISSUE THREAD

**Issue by diggy128** [BenoitDuffez/AndroidCupsPrint#85] opened 2017-08-03 21:26 UTC
Currently only A4 paper size is selectable. Since I have a couple of label printers with custom paper sizes, it would be awesome to pull paper sizes from the printer's ppd.

I can provide sample PPD files if needed.

**Comment by BenoitDuffez** [comment] 2017-08-04 08:34
I think this is a (clearer) duplicate of #78. I'll have to investigate.

**Comment by BenoitDuffez** [comment] 2018-09-27 20:03
Actually I don't know the PPD file format and how this can help detect the paper sizes. The printer should advertise the list of paper sizes it supports.

If you can help, please reopen.

**Closed by BenoitDuffez** 2018-09-27 20:03 UTC
Labels: enhancement, help wanted

**Comment by chrisapps4u** [comment] 2018-09-30 15:40
Please check, if you see your paper sizes in general settings of these printers in the cups website. I think your PPD-File isn't correct. AndroidCupsPrint just read the paper size from the server response and not out of the PPD-File.
