### ISSUE TITLE
No TLS encryption

### ISSUE THREAD

**Issue by sv1** [BenoitDuffez/AndroidCupsPrint#42] opened 2017-01-28 08:58 UTC
Hello,

I am trying to use AndroidCupsPrint on a Samsung Galaxy J5 with Android 6.0.1. Unfortunately I can not print at all.

Bellow you can see the error from CUPS error.log

E [28/Jan/2017:10:11:17 +0200] Unable to encrypt connection from 192.168.1.54 - A TLS fatal alert has been received.
E [28/Jan/2017:10:16:28 +0200] [Client 25] Returning IPP client-error-bad-request for Print-Job (https://192.168.1.2/printers/Deskjet_2640) from 192.168.1.54

This is on a Debian 8.7 with cups 1.7.5

Thanks
AK

**Comment by BenoitDuffez** [comment] 2017-01-30 21:20
Can you increase the verbosity to get more details? I'm puzzled and I don't know what could be the issue here.
Also, device logs would be useful too.

**Comment by sv1** [comment] 2017-02-02 09:53
D [02/Feb/2017:11:50:08 +0200] [Client 20] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:50:08 +0200] [Client 20] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 20] Encrypting connection.
D [02/Feb/2017:11:50:08 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 20] POST /printers/ HTTP/1.1
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:50:08 +0200] [Client 20] No authentication data provided.
D [02/Feb/2017:11:50:08 +0200] [Client 20] 1.1 CUPS-Get-Printers 7
D [02/Feb/2017:11:50:08 +0200] CUPS-Get-Printers https://192.168.1.2/printers/
D [02/Feb/2017:11:50:08 +0200] [Client 20] Returning IPP successful-ok for CUPS-Get-Printers (https://192.168.1.2/printers/) from 192.168.1.54
D [02/Feb/2017:11:50:08 +0200] [Client 20] Content-Length: 603
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 20] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=603, response=0x7fb3a1334150(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:50:08 +0200] [Client 20] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:50:08 +0200] [Client 20] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:50:08 +0200] [Client 20] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 21] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:50:08 +0200] [Client 21] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 21] Encrypting connection.
D [02/Feb/2017:11:50:08 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 21] POST /printers/ HTTP/1.1
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:50:08 +0200] [Client 21] No authentication data provided.
D [02/Feb/2017:11:50:08 +0200] [Client 21] 1.1 CUPS-Get-Default 8
D [02/Feb/2017:11:50:08 +0200] CUPS-Get-Default https://192.168.1.2/printers/
D [02/Feb/2017:11:50:08 +0200] CUPS-Get-Default client-error-not-found: No default printer.
D [02/Feb/2017:11:50:08 +0200] [Client 21] Returning IPP client-error-not-found for CUPS-Get-Default (https://192.168.1.2/printers/) from 192.168.1.54
D [02/Feb/2017:11:50:08 +0200] [Client 21] Content-Length: 113
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 21] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=113, response=0x7fb3a133e8d0(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:50:08 +0200] [Client 21] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:50:08 +0200] [Client 21] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:50:08 +0200] [Client 21] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 22] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:50:08 +0200] [Client 22] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 22] Encrypting connection.
D [02/Feb/2017:11:50:08 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 22] POST /printers/Deskjet_2640 HTTP/1.1
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:50:08 +0200] [Client 22] No authentication data provided.
D [02/Feb/2017:11:50:08 +0200] [Client 22] 1.1 Get-Printer-Attributes 9
D [02/Feb/2017:11:50:08 +0200] Get-Printer-Attributes https://192.168.1.2/printers/Deskjet_2640
D [02/Feb/2017:11:50:08 +0200] [Client 22] Returning IPP successful-ok for Get-Printer-Attributes (https://192.168.1.2/printers/Deskjet_2640) from 192.168.1.54
D [02/Feb/2017:11:50:08 +0200] [Client 22] Content-Length: 1008
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 22] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=1008, response=0x7fb3a1355580(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:50:08 +0200] [Client 22] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:50:08 +0200] [Client 22] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:50:08 +0200] [Client 22] Waiting for request.
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 17] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:50:08 +0200] [Client 17] Closing connection.
D [02/Feb/2017:11:50:08 +0200] SSL shutdown successful!
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:50:08 +0200] [Client 17] Waiting for socket close.
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:08 +0200] [Client 17] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:50:08 +0200] [Client 17] Closing connection.
D [02/Feb/2017:11:50:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:50:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:50:09 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 17] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:51:07 +0200] [Client 17] Waiting for request.
D [02/Feb/2017:11:51:07 +0200] Report: clients=6
D [02/Feb/2017:11:51:07 +0200] Report: jobs=116
D [02/Feb/2017:11:51:07 +0200] Report: jobs-active=0
D [02/Feb/2017:11:51:07 +0200] Report: printers=2
D [02/Feb/2017:11:51:07 +0200] Report: stringpool-string-count=1351
D [02/Feb/2017:11:51:07 +0200] Report: stringpool-alloc-bytes=7448
D [02/Feb/2017:11:51:07 +0200] Report: stringpool-total-bytes=25072
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 17] Encrypting connection.
D [02/Feb/2017:11:51:07 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 17] POST /printers/ HTTP/1.1
D [02/Feb/2017:11:51:07 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:51:07 +0200] [Client 17] No authentication data provided.
D [02/Feb/2017:11:51:07 +0200] [Client 17] 1.1 CUPS-Get-Printers 10
D [02/Feb/2017:11:51:07 +0200] CUPS-Get-Printers https://192.168.1.2/printers/
D [02/Feb/2017:11:51:07 +0200] [Client 17] Returning IPP successful-ok for CUPS-Get-Printers (https://192.168.1.2/printers/) from 192.168.1.54
D [02/Feb/2017:11:51:07 +0200] [Client 17] Content-Length: 603
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 17] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=603, response=0x7fb3a12e5160(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:51:07 +0200] [Client 17] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:51:07 +0200] [Client 17] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:51:07 +0200] [Client 17] Waiting for request.
D [02/Feb/2017:11:51:07 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 18] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:07 +0200] [Client 18] Closing connection.
D [02/Feb/2017:11:51:07 +0200] SSL shutdown successful!
D [02/Feb/2017:11:51:07 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:07 +0200] [Client 18] Waiting for socket close.
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 18] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:07 +0200] [Client 18] Closing connection.
D [02/Feb/2017:11:51:07 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 18] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:51:07 +0200] [Client 18] Waiting for request.
D [02/Feb/2017:11:51:07 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:07 +0200] [Client 18] Encrypting connection.
D [02/Feb/2017:11:51:08 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 18] POST /printers/ HTTP/1.1
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] [Client 18] No authentication data provided.
D [02/Feb/2017:11:51:08 +0200] [Client 18] 1.1 CUPS-Get-Default 11
D [02/Feb/2017:11:51:08 +0200] CUPS-Get-Default https://192.168.1.2/printers/
D [02/Feb/2017:11:51:08 +0200] CUPS-Get-Default client-error-not-found: No default printer.
D [02/Feb/2017:11:51:08 +0200] [Client 18] Returning IPP client-error-not-found for CUPS-Get-Default (https://192.168.1.2/printers/) from 192.168.1.54
D [02/Feb/2017:11:51:08 +0200] [Client 18] Content-Length: 113
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 18] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=113, response=0x7fb3a1322d20(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:51:08 +0200] [Client 18] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:51:08 +0200] [Client 18] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:51:08 +0200] [Client 18] Waiting for request.
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:08 +0200] [Client 19] Closing connection.
D [02/Feb/2017:11:51:08 +0200] SSL shutdown successful!
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] [Client 19] Waiting for socket close.
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:08 +0200] [Client 19] Closing connection.
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] Accepted from 192.168.1.54:631 (IPv4)
D [02/Feb/2017:11:51:08 +0200] [Client 19] Waiting for request.
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] Encrypting connection.
D [02/Feb/2017:11:51:08 +0200] Connection from 192.168.1.54 now encrypted.
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] POST /printers/Deskjet_2640 HTTP/1.1
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] [Client 19] No authentication data provided.
D [02/Feb/2017:11:51:08 +0200] [Client 19] 1.1 Get-Printer-Attributes 12
D [02/Feb/2017:11:51:08 +0200] Get-Printer-Attributes https://192.168.1.2/printers/Deskjet_2640
D [02/Feb/2017:11:51:08 +0200] [Client 19] Returning IPP successful-ok for Get-Printer-Attributes (https://192.168.1.2/printers/Deskjet_2640) from 192.168.1.54
D [02/Feb/2017:11:51:08 +0200] [Client 19] Content-Length: 1008
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 19] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=1008, response=0x7fb3a1319d20(IPP_IDLE), pipe_pid=0, file=-1
D [02/Feb/2017:11:51:08 +0200] [Client 19] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0
D [02/Feb/2017:11:51:08 +0200] [Client 19] bytes=0, http_state=0, data_remaining=0
D [02/Feb/2017:11:51:08 +0200] [Client 19] Waiting for request.
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 20] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:08 +0200] [Client 20] Closing connection.
D [02/Feb/2017:11:51:08 +0200] SSL shutdown successful!
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] [Client 20] Waiting for socket close.
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:08 +0200] [Client 20] HTTP_STATE_WAITING Closing on EOF
D [02/Feb/2017:11:51:08 +0200] [Client 20] Closing connection.
D [02/Feb/2017:11:51:08 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [02/Feb/2017:11:51:08 +0200] cupsd is not idle any more, canceling shutdown.
D [02/Feb/2017:11:51:09 +0200] cupsd is not idle any more, canceling shutdown.

**Comment by BenoitDuffez** [comment] 2017-02-02 10:58
There is no `client-error-bad-request` occurrence in this log. It looks like it worked.

**Comment by sv1** [comment] 2017-02-03 15:03
It looks like it worked, but it didn't.

I got a "Sorry this didn't work" on the phone and a retry button. But
nothing ever happens!!!

**Comment by BenoitDuffez** [comment] 2017-02-03 15:28
With this I have too little information about the issue, I don't even know if the problem is located in the app or the server.

Please indicate how can I reproduce the issue; or at least how you do so, while providing logs.

Other than that, I'm afraid I won't be able to do anything.

**Comment by BenoitDuffez** [comment] 2017-04-12 22:30
Please comment if you still have the issue. Closing for now.

**Closed by BenoitDuffez** 2017-04-12 22:30 UTC
Labels: invalid
