### ISSUE TITLE
86acef4 seems to make application crash on mdns query

### ISSUE THREAD

**Issue by Gemba** [BenoitDuffez/AndroidCupsPrint#14] opened 2016-03-01 22:51 UTC
Building/assembling works but when querying for printers the app crashes.

Workaround: Resurrect JfSSLScheme.java class and add

```
android {
    useLibrary 'org.apache.http.legacy'
    ...
```

in app/build.gradle.

But I guess the workaround is not the outcome you were aiming at...

```
V/WindowManager(10292): not Base app: Adding window Window{38b0d0bc u0 com.android.settings/com.android.settings.SubSettings} at 7 of 13
D/mali_winsys(14025): new_window_surface returns 0x3000
I/ActivityManager(10292): Start proc 14212:io.github.benoitduffez.cupsprint/u0a123 for service io.github.benoitduffez.cupsprint/.printservice.CupsService
W/InputMethodManagerService(10292): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@8284afd attribute=null, token = android.os.BinderProxy@34f08124
E/AndroidRuntime(14212): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(14212): Process: io.github.benoitduffez.cupsprint, PID: 14212
E/AndroidRuntime(14212): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(14212):    at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(14212):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(14212):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(14212):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(14212):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(14212):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(14212):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(14212):    at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(14212): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jonbanjo/ssl/JfSSLScheme;
E/AndroidRuntime(14212):    at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:212)
E/AndroidRuntime(14212):    at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:140)
E/AndroidRuntime(14212):    at org.cups4j.operations.IppOperation.request(IppOperation.java:75)
E/AndroidRuntime(14212):    at org.cups4j.operations.cups.CupsGetPrintersOperation.getPrinters(CupsGetPrintersOperation.java:51)
E/AndroidRuntime(14212):    at org.cups4j.CupsClient.getPrinters(CupsClient.java:76)
E/AndroidRuntime(14212):    at org.cups4j.CupsClient.getPrinter(CupsClient.java:96)
E/AndroidRuntime(14212):    at com.jonbanjo.detect.MdnsServices.scan(MdnsServices.java:236)
E/AndroidRuntime(14212):    at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession.scanPrinters(CupsPrinterDiscoverySession.java:250)
E/AndroidRuntime(14212):    at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession.access$000(CupsPrinterDiscoverySession.java:63)
E/AndroidRuntime(14212):    at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession$1.doInBackground(CupsPrinterDiscoverySession.java:83)
E/AndroidRuntime(14212):    at io.github.benoitduffez.cupsprint.printservice.CupsPrinterDiscoverySession$1.doInBackground(CupsPrinterDiscoverySession.java:80)
E/AndroidRuntime(14212):    at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(14212):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(14212):    ... 4 more
E/AndroidRuntime(14212): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jonbanjo.ssl.JfSSLScheme" on path: DexPathList[[zip file "/data/app/io.github.benoitduffez.cupsprint-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(14212):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(14212):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(14212):    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(14212):    ... 17 more
E/AndroidRuntime(14212):    Suppressed: java.lang.ClassNotFoundException: com.jonbanjo.ssl.JfSSLScheme
E/AndroidRuntime(14212):        at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(14212):        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(14212):        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(14212):        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(14212):        ... 18 more
E/AndroidRuntime(14212):    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by BenoitDuffez** [comment] 2016-03-02 08:31
I couldn't find uses of said class. Is it by reflection?
On my setup (at aca9b4f) the mDNS query runs fine and finds my printer. No crash.
How did you reproduce?

As per my outcome, I just removed the class and dependency because they were marked as not used by the IDE, and removing them didn't have any impact on my (limited) testing.

**Comment by Gemba** [comment] 2016-03-04 12:16
Still persists on 21145ae. The issue does not happen every time but it is quite likely to happen.
It happens whenever a CUPS server advertises a secured IPP connection via mDNS. So if you use at least a bogus cert (which most OOTB installations of CUPS do) you will run into it:

1. Remove cache and data from device, uninstall app, install the app with the commit given above
2. After installation tap enable print service
3. If no printers are found use the back button, latest then it will crash
4. If it not does crash use wireshark to sniff the mDNS traffic to see if _ipps._tcp.local gets promoted by the CUPS server (Display filter setting in wireshark: `dns and udp.port eq 5353`).

The JfSslScheme class is referenced by the modified cups4j-library. 
One solution may be removing the query for IPPS in MDnsServices.scan(). For me it is a bad idea because I guess SSL should be the new norm.

Please let me know if you can reproduce this issue.

**Comment by BenoitDuffez** [comment] 2016-10-22 20:34
OK I fucked up the branches/commits big time once again. I had to do a lot of cleanup because I started working on the wrong branch, then merged on another wrong branch again, and I had to move all code to develop because I pushed to master (which should've contained the current code published to the play store).

Long story short, now the develop branch contains:
* everything as source instead of jars (thanks to the work done on the fdroid branch)
* the JfSSLScheme class so that your SSL enabled printers won't crash anymore

I was able to print something over SSL today. Can you tell me if a464f3b is working for you?

**Comment by BenoitDuffez** [comment] 2016-10-23 23:28
If you could also check f7ed730. I removed all deprecated code (HttpClient and stuff), plus implemented a better SSL management (ability to store server certs to a local key store, very useful for self-signed certs).

Tell me if both are working or not.
Thanks!

**Comment by BenoitDuffez** [comment] 2016-10-25 22:46
OK I have fixed bugs. I didn't know Android remembered the printers for so long, so I did my tests over HTTP :(

Now I have forced my CUPS daemon to use SSL, and I am more careful when testing. It now works as expected.
If you want to test, use at least 669ec7e. You have to accept two prompts (at least on my setup): untrusted certificate, then untrusted host.

Thanks!

**Comment by BenoitDuffez** [comment] 2016-10-27 10:58
Test the latest beta if you don't want to compile. Link is on README file on master.

**Comment by BenoitDuffez** [comment] 2017-01-24 21:40
I don't think this is still valid, it should be fixed on latest version. Closing.

**Closed by BenoitDuffez** 2017-01-24 21:40 UTC
Labels: bug
