### ISSUE TITLE
Not working on Huawei Y360-U31

### ISSUE THREAD

**Issue by StevanWhite** [BenoitDuffez/AndroidCupsPrint#55] opened 2017-03-19 12:10 UTC
Huawei Y360-U31
Android 4.4.2
German language

Installed, but do not see a "Printing" or "Drucken" item in the Settings (All) menu.
Also do not see an icon.
But it does show in the Apps list.

**Comment by BenoitDuffez** [comment] 2017-03-19 14:58
It shouldn't show in the launcher, that's expected.
You should have a recent Android version and the print options should be in the settings app somewhere. I can't help you more because I can't test on your device.

**Comment by StevanWhite** [comment] 2017-03-24 10:33
Hi Benoit,

I would be glad to help debug it, if you can sort out a way. (Write a debug file or something?)

I switched the phone's language to English, to no avail.  Still nothing about printing in the Settings app.

**Comment by BenoitDuffez** [comment] 2017-03-24 10:37
You can't actually _debug_, since as far as I understand, the problem is on the OS you use and not this app.

Maybe I could add in the launcher app (added in 1.4.0, available on the play store as a beta) a button the triggers an intent to the settings app. But even this would likely not solve the issue, since your OS uses a custom settings app and the intent is very likely to fail on your device.

Really, search again the settings app or stop buying devices with a non-vanilla Android version. Sorry.

**Comment by BenoitDuffez** [comment] 2017-04-12 22:31
Please comment if you need further help from me. Closing for now.

**Closed by BenoitDuffez** 2017-04-12 22:31 UTC
Labels: invalid
