### ISSUE TITLE
Unable to Print Photos

### ISSUE THREAD

**Issue by dob99** [BenoitDuffez/AndroidCupsPrint#128] opened 2018-10-09 20:45 UTC
Running on a Galaxy Tab A6, I've tried printing a photo to both a Canon inkjet and a Samsung laser. I've tried printing from Google Photos and Samsung's Gallery app. The message "EBADF (bad file descriptor)" pops up very briefly on the tablet. The end of the server error log is attached.
[cups.error.log](https://github.com/BenoitDuffez/AndroidCupsPrint/files/2462127/cups.error.log)

 I was able to print a web page on both printers with no problems.

**Comment by BenoitDuffez** [comment] 2018-10-15 12:32
This is a duplicate of #116. Not fixed in the production version on the Play Store, but available in the beta version. See README.md for more details about the beta.

**Closed by BenoitDuffez** 2018-10-15 12:32 UTC
